# Copyright 2013 The Flutter Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

name: pkg_test_demo
publish_to: none

# Do not add any dependencies that require more than what is provided in
# //third_party/dart/pkg or //third_party/dart/third_party/pkg.

# If you do add packages here, make sure you can run `pub get --offline`, and
# check the .packages and .package_config to make sure all the paths are
# relative to this directory into //third_party/dart

environment:
  sdk: '>=3.2.0-0 <4.0.0'

dev_dependencies:
  test:

dependency_overrides:
  _fe_analyzer_shared:
    path: ../../third_party/dart/pkg/_fe_analyzer_shared
  _macros:
    path: ../../third_party/dart/pkg/_macros
  analyzer:
    path: ../../third_party/dart/pkg/analyzer
  args:
    path: ../../third_party/dart/third_party/pkg/args
  async:
    path: ../../third_party/dart/third_party/pkg/async
  boolean_selector:
    path: ../../third_party/dart/third_party/pkg/boolean_selector
  collection:
    path: ../../third_party/dart/third_party/pkg/collection
  convert:
    path: ../../third_party/dart/third_party/pkg/convert
  coverage:
    path: ../../third_party/pkg/coverage
  crypto:
    path: ../../third_party/dart/third_party/pkg/crypto
  file:
    path: ../../third_party/dart/third_party/pkg/file/packages/file
  frontend_server_client:
    path: ../../third_party/dart/third_party/pkg/webdev/frontend_server_client
  glob:
    path: ../../third_party/dart/third_party/pkg/glob
  http_multi_server:
    path: ../../third_party/dart/third_party/pkg/http_multi_server
  http_parser:
    path: ../../third_party/dart/third_party/pkg/http_parser
  io:
    path: ../../third_party/pkg/io
  js:
    path: ../../third_party/dart/pkg/js
  logging:
    path: ../../third_party/dart/third_party/pkg/logging
  macros:
    path: ../../third_party/dart/pkg/macros
  matcher:
    path: ../../third_party/dart/third_party/pkg/matcher
  meta:
    path: ../../third_party/dart/pkg/meta
  mime:
    path: ../../third_party/dart/third_party/pkg/mime
  node_preamble:
    path: ../../third_party/pkg/node_preamble
  package_config:
    path: ../../third_party/dart/third_party/pkg/package_config
  path:
    path: ../../third_party/dart/third_party/pkg/path
  pool:
    path: ../../third_party/dart/third_party/pkg/pool
  pub_semver:
    path: ../../third_party/dart/third_party/pkg/pub_semver
  shelf:
    path: ../../third_party/dart/third_party/pkg/shelf/pkgs/shelf
  shelf_packages_handler:
    path: ../../third_party/dart/third_party/pkg/shelf/pkgs/shelf_packages_handler
  shelf_static:
    path: ../../third_party/dart/third_party/pkg/shelf/pkgs/shelf_static
  shelf_web_socket:
    path: ../../third_party/dart/third_party/pkg/shelf/pkgs/shelf_web_socket
  source_map_stack_trace:
    path: ../../third_party/dart/third_party/pkg/source_map_stack_trace
  source_maps:
    path: ../../third_party/dart/third_party/pkg/source_maps
  source_span:
    path: ../../third_party/dart/third_party/pkg/source_span
  stack_trace:
    path: ../../third_party/dart/third_party/pkg/stack_trace
  stream_channel:
    path: ../../third_party/dart/third_party/pkg/stream_channel
  string_scanner:
    path: ../../third_party/dart/third_party/pkg/string_scanner
  term_glyph:
    path: ../../third_party/dart/third_party/pkg/term_glyph
  test:
    path: ../../third_party/dart/third_party/pkg/test/pkgs/test
  test_api:
    path: ../../third_party/dart/third_party/pkg/test/pkgs/test_api
  test_core:
    path: ../../third_party/dart/third_party/pkg/test/pkgs/test_core
  typed_data:
    path: ../../third_party/dart/third_party/pkg/typed_data
  vm_service:
    path: ../../third_party/dart/pkg/vm_service
  watcher:
    path: ../../third_party/dart/third_party/pkg/watcher
  web:
    path: ../../third_party/dart/third_party/pkg/web
  web_socket:
    path: ../../third_party/dart/third_party/pkg/http/pkgs/web_socket
  web_socket_channel:
    path: ../../third_party/dart/third_party/pkg/web_socket_channel
  webkit_inspection_protocol:
    path: ../../third_party/dart/third_party/pkg/webkit_inspection_protocol
  yaml:
    path: ../../third_party/dart/third_party/pkg/yaml
